version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/application"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/cdk"
    schedule:
      interval: "daily"
